### ISSUE TITLE
release page上での配布形態について

### ISSUE THREAD

**Issue by falconws** [nakanotti/CocoaInput#14]
@nakanotti 
現在zipで配布して頂いていると思いますが、jar形式で配布することはできませんか？
`ferium` (https://github.com/gorilla-devs/ferium) というMOD Managerを使っているのですが、

```
Note
The GitHub repository has to release JAR files in their Releases for ferium to download, or else it will refuse to be added
```

という記載があり、jarでの配布でなければ対応していないようで・・。
また、こういう制限があるのは、本来はjar形式で配布するのが適切というか標準？なのかなとも思ったので、
Issueあげさせて頂きます。
ご検討頂ければ幸いです。

**Comment by nakanotti** [comment]
ありがとうございます。
jar は zlib で圧縮されているので、zip に zip している様なものですから、そもそもナンセンスなんですよね。
次回以降、jar をそのまま配布する形式にさせて頂きます。

**Comment by nakanotti** [comment]
https://github.com/nakanotti/CocoaInput/issues/15#issuecomment-1565890581
