### ISSUE TITLE
4.0.7-PREVIEW not working on Linux

### ISSUE THREAD

**Issue by falconws** [nakanotti/CocoaInput#15]
**Describe the bug**

バージョン4.0.7-PREVIEWをmodsフォルダの中に入れた状態でMinecraftを起動すると、クラッシュします。

**Describe the environment** 
 - OS: Linux mint 21.1 vera
 - Arch: x86_64
 - IME: fcitx/mozc
 - Minecraft: 1.19.4
 - ModVersion: 4.0.7
 - ModSetting: ?

**To Reproduce**
1. [CocoaInput-1.19.4-4.0.7-PREVIEW.zip](https://github.com/nakanotti/CocoaInput/releases/download/4.0.7-PREVIEW/CocoaInput-1.19.4-4.0.7-PREVIEW.zip)をダウンロードする
2. unzipする
3. `CocoaInput-1.19.4-fabric-4.0.7-PREVIEW.jar` をFabricのmods/ フォルダに移動する
4. Minecraftを起動する
5. クラッシュする

**Logs(URL)**
クラッシュログを添付します。
[hs_err_pid41506.log](https://github.com/nakanotti/CocoaInput/files/11394899/hs_err_pid41506.log)

**Additional context**
Version 4.0.5 の時は正常に動作しました。
Version 4.0.6 を試しに 1.19.4 で動かすと（サポート外だが）、一応動くものの入力欄に変なゴミ文字が
混ざってしまい実用的ではありませんでした。

**Comment by nakanotti** [comment]
報告ありがとうございます。
確認します。

**Comment by nakanotti** [comment]
すみません、どうやらネイティブライブラリが、古い方のものに置き換わっていたようです。
差し替えたものに更新します。

**Comment by nakanotti** [comment]
https://github.com/nakanotti/CocoaInput/releases/tag/4.0.7-PREVIEW
ソースに変更はないため、バイナリだけ差し替えました。（サボり）
まだ作業時間があまりとれないため、こちらの確認不足の状態で申し訳ありません。

**Comment by nakanotti** [comment]
[4.0.7-PREVIEW2](https://github.com/nakanotti/CocoaInput/releases/tag/4.0.7-PREVIEW2) に更新しました。
@falconws さん、可能であれば、再度こちらで動作確認をお願いできますでしょうか？

**Comment by falconws** [comment]
@nakanotti ありがとうございます。
確認したところ、完璧に動作しました！

ちなみに、jarで配布する形にして頂いたおかげで、feriumにも対応して更新しやすくなりました！

```bash
falconws@ghast: $ ferium add nakanotti/CocoaInput
Adding mod... ✓ CocoaInput
falconws@ghast:~$ ferium list
AdvancementInfo                               Modrinth   G1epq3jN
Cloth Config API                              Modrinth   9s6osm5g
CocoaInput                                    GitHub     nakanotti/CocoaInput
Fabric API                                    Modrinth   P7dR8mSH
Fabric Language Kotlin                        Modrinth   Ha28R6CL
```

この後 `ferium upgrade` で `CocoaInput-1.19.4-fabric-4.0.7-PREVIEW2.jar` を拾ってきて確認したところ、
無事に動作しました。
