### ISSUE TITLE
Pending text in `EditBox`es does not render with Caxton

### ISSUE THREAD

**Issue by bluebear94** [nakanotti/CocoaInput#29]
**Describe the bug:** When [Caxton](https://modrinth.com/mod/caxton) is installed, text that is being edited in the IME will not render in `EditBox`es.

**Describe the environment:** 
 - OS: Linux (EndeavourOS)
 - Arch: x86_64
 - IME: IBus
 - Minecraft: 1.20.1
 - ModVersion: CocoaInput 4.0.9 (fbbcfbe), Caxton 0.5.0-alpha.3
 - ModSetting: Fabric

**To Reproduce**
1. Install Caxton and CocoaInput
2. Select an edit box (such as the one in the world selection screen or the chat box)
3. Try to enter something using an IME
4. Notice that the characters being entered do not render

**Logs(URL)**
[latest.log (with debug log level)](https://github.com/nakanotti/CocoaInput/files/12543980/latest.log)

**Additional context**

See [the corresponding issue at Caxton’s repository](https://gitlab.com/Kyarei/caxton/-/issues/59).

Caxton [modifies the behavior of `EditBox`](https://gitlab.com/Kyarei/caxton/-/blob/master/common/src/main/java/xyz/flirora/caxton/mixin/gui/TextFieldWidgetMixin.java?ref_type=heads) (uses Yarn mappings) to handle bidirectional text and complex scripts properly. As part of these changes, it caches the `CaxtonText`[^1] for the current contents of the `EditBox` whenever a method that updates these contents (such as `setValue`, `insertText`, or `setSuggestion`) is called.

Meanwhile, in CocoaInput, [`EditBoxWrapper#setText`](https://github.com/nakanotti/CocoaInput/blob/fbbcfbe0a209b15b98e41f6f0f555ad49a48ea0f/src/main/java/jp/axer/cocoainput/wrapper/EditBoxWrapper.java#L37) sets the `EditBox#value` field directly, preventing Caxton from knowing that the contents of the edit box has changed.

[^1]: In Caxton, [`CaxtonText`](https://gitlab.com/Kyarei/caxton/-/blob/master/common/src/main/java/xyz/flirora/caxton/layout/CaxtonText.java?ref_type=heads) describes the layout of a piece of text, and it is also the form internally used for rendering text.

**Comment by nakanotti** [comment]
Thank you for your detail information!
Fixed at aba37a536c444a29dddca59eaa6a2200a3b76cad

**Comment by nakanotti** [comment]
@bluebear94 

There are still some problems with the caret display, but I think you can confirm that it works.

https://github.com/nakanotti/CocoaInput/releases/tag/1.20.1-PREVIEW2

**Comment by bluebear94** [comment]
I wonder why the code originally set the value of `EditBox#value` directly in the first place. Is it because inserting the pending text should bypass the length limit and `EditBox#filter`?

**Comment by nakanotti** [comment]
Unfortunately, I'm not the original author, so I don't know.
I am keeping the changes to a minimum in the hope that the original author will return.

I have no experience creating a MOD from scratch, so I appreciate your questions and reports, allowing me to notice problems.
Thank you!
