### ISSUE TITLE
Will 1.20.4 become supported?

### ISSUE THREAD

**Issue by DasCrystal** [nakanotti/CocoaInput#36]
Cause of the huge change of 1.20.5, 1.20.4 might be a next major version for mod players, as this consider, I want to ask, will 1.20.4 become supported?

**Comment by MusclePr** [comment]
[1.20.2-PREVIEW2](https://github.com/nakanotti/CocoaInput/releases/tag/1.20.2-PREVIEW2)
This release supports 1.20.2 - 1.20.4.

**Comment by DasCrystal** [comment]
> [1.20.2-PREVIEW2](https://github.com/nakanotti/CocoaInput/releases/tag/1.20.2-PREVIEW2) This release supports 1.20.2 - 1.20.4.

Thank you, it works.
