### ISSUE TITLE
Doesn't work Linux env

### ISSUE THREAD

**Issue by falconws** [nakanotti/CocoaInput#7]
@nakanotti 
[CocoaInput-1.19-4.0.5-PREVIEW3.zip](https://github.com/nakanotti/CocoaInput/releases/download/PREVIEW3/CocoaInput-1.19-4.0.5-PREVIEW3.zip)
を試しましたが、Linux環境では動作しませんでした。
crashはせず立ち上がりますが、MODを入れていないのと変わらず日本語入力不能でした。

```
uname -a
Linux hostname 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una
```

`build_lib_for_x11.sh` でbuildしたものもリリースに含まれていますか？

**Comment by nakanotti** [comment]
> build_lib_for_x11.sh でbuildしたものもリリースに含まれていますか？

はい。含まれておりますが、厳密には私がビルドしたものは含まれておりません。
オリジナルの1.18から変更差分が無かったため、以下のアーカイブに含まれているものと同じものが含まれております。
[CocoaInput-1.18-fabric-4.0.4.jar](https://www.curseforge.com/minecraft/mc-mods/cocoainput/files/3554724)

ちなみに、1.18.xの時は問題なかったでしょうか？
私の手元にまだ確認環境が用意できていないため、申し訳ありませんがオリジナルの1.18でも再現するか確認して頂けると幸いです。

**Comment by falconws** [comment]
@nakanotti 

> ちなみに、1.18.xの時は問題なかったでしょうか？
私の手元にまだ確認環境が用意できていないため、申し訳ありませんがオリジナルの1.18でも再現するか確認して頂けると幸いです。

はい。1.18.xの時は問題なく動作しておりました。
ちなみにですが、

> crashはせず立ち上がりますが、MODを入れていないのと変わらず日本語入力不能でした。

と記載してしまったのですが、これ .zip のまま mods/ 内に配置してしまっていた為でした。
.zip を展開して .jar で配置した場合、crash します。

@nakanotti さんのCocoa Input master branchを取得して、
build_lib_for_x11.sh を実行した後、 fabric/gradlew build を実行して手元で Cocoainput-1.19-fabric-4.0.5.jar
を生成して試したりもしましたが、同じくcrashしました。
オリジナルの開発者が復帰してくれてアップデートしてくれるのが望ましいのですが、応答が無いみたいなので、
@nakanotti さんに期待してしまっていますが、Linux環境でも動作する様に改修できそうでしょうか・・？

**Comment by nakanotti** [comment]
crashの確認ですが、 `Process crashed with exit code 6` で落ちますか？
こちらでも再現を確認したのですが、WSL2上で動作させているため同じ症状か不明です。
可能であればログを添付していただけると幸いです。

**Comment by falconws** [comment]
@nakanotti 
`CocoaInput-1.19-fabric-4.0.5-PREVIEW.jar` で試しました。
MD5: `12cb2fe2305d6c86ebcf4348665e1a38`

logを添付します。

[hs_err_pid4241.log](https://github.com/nakanotti/CocoaInput/files/9179141/hs_err_pid4241.log)

**Comment by nakanotti** [comment]
ログありがとうございます。こちらを試してもらえますでしょうか？
[CocoaInput-1.19-fabric-4.0.5-PREVIEW_for_x11.jar.zip](https://github.com/nakanotti/CocoaInput/files/9179370/CocoaInput-1.19-fabric-4.0.5-PREVIEW_for_x11.jar.zip)

**Comment by nakanotti** [comment]
e4b04b088030ff2964f977454dee66f86053a4e6 にて修正しました。

**Comment by falconws** [comment]
@nakanotti おお！・・無事に動作しました！
ご対応頂きありがとうございます 🙇‍♂️ 

logから分かったのでしょうか？修正箇所拝見する限り、Java部分ではなくCで書かれているNative Libraryの部分のようなので、
難易度高いように見受けられるのですが、いきなりmaster branchにpushしている辺り自信お有りだったと思います。
凄いですね・・！どうやって解決に至ったのか差し支えなければちらっとご教示頂けると・・

**Comment by nakanotti** [comment]
ご確認ありがとうございます！

「不正メモリアクセス」ということが解ってしまえば、難易度はそれほど高くなかったです。
https://github.com/nakanotti/CocoaInput/issues/7#issuecomment-1193703044 に記載した上手くいっているときのログと、
```
Searching _GLFWwindowx11 from GLFWwindow ptr...
Found offset:832 ,_GLFWwindowX11(0x7f343dc7b860)=GLFWwindow(0x7f343dc7b520)+832 
XIC mem address:0x7f343d983ef0
```
上手くいっていないログを見比べると、
```
Searching _GLFWwindowx11 from GLFWwindow ptr...
Found offset:1136 ,_GLFWwindowX11(0x7faed6356c00)=GLFWwindow(0x7faed6356790)+1136 
XIC mem address:0x247
```
XIC mem address の値がアドレスを示すものにしては、0x247というのは明らかに小さいんですよね。
他のアドレスが0x7f0000000000以上を示していて、ログに出力されたレジスタ周りの値を見ても、
同様の範囲である事から十中八九、この0x247にアクセスするとcrashするはず。
（頂いたエラーログにあった「SIGSEGV」も、不正なメモリアドレスアクセスによるセグメントバイオレーションでした。）
で、この出力をしているソースコードを見ると、_GLFWwindowX11のメンバーicの位置を読み取ろうとしています。
https://github.com/nakanotti/CocoaInput/blob/e4b04b088030ff2964f977454dee66f86053a4e6/libcocoainput/x11/libx11cocoainput.c#L168-L180
_GLFWwindowX11で検索すると.hにありました。
https://github.com/nakanotti/CocoaInput/blob/2db8a0db017b728a787b063ff3405e981c0f2de4/libcocoainput/x11/libx11cocoainput.h#L17-L44
これを同様にググると、GLFWのヘッダファイルが出てき、GLFWがオープンソースである事が解りました。
この構造体のicを参照していたけど、おそらく1.19になってGLFWの新しいやつを使ったんだろうと推察したので、
ちょうど、原作者がコメントアウトしている21行目の箇所が最新版との差分になっていましたので、それを解除しただけです。
（原作者であれば、たぶん、ログだけですぐにピンと来て分かったと思われます。）
頂いたエラーログが私と同じだったので、手元で修正確認済みのお試しjarを貼った次第です。

# その後すぐにmasterにマージしたのは安全性が高い事もありますが、ブランチ切るのが面倒だったので正直サボりました。(^^;

**Comment by falconws** [comment]
@nakanotti 詳細な解説をして頂き、まことにありがとうございます！ 🙇‍♂️ 
いやー・・ Low Layer の知識がないと、これは解決不能な問題ですね・・・。
私にはこの内容は無理でした〜・・。
素晴らしいEngineeringをして頂き、本当に頭が下がる思いです！
この度は本当にありがとうございました！どれくらい居るか分かりませんが、
LinuxユーザのMinecraft Playerも救われました〜

（添付したlogについては、一応削除しておきますね）
